# Generated by Django 5.2.6 on 2025-09-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сообщение из формы контактов',
                'verbose_name_plural': 'Сообщения из формы контактов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default="Pro<span style='color: #87B741;'>&#129734;</span>ПИТАНИЕ", max_length=200, verbose_name='Заголовок героя')),
                ('hero_subtitle', models.TextField(default='Гастрономическое кафе с полезными и вкусными блюдами из натуральных продуктов', verbose_name='Подзаголовок героя')),
                ('hero_button_text', models.CharField(default='Смотреть меню', max_length=50, verbose_name='Текст кнопки героя')),
                ('about_title', models.CharField(default='О нашем кафе', max_length=200, verbose_name="Заголовок блока 'О нас'")),
                ('about_text', models.TextField(default='Pro&#129734;ПИТАНИЕ — это место, где вкус и польза идут рука об руку...', verbose_name="Текст блока 'О нас'")),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name="Изображение блока 'О нас'")),
                ('delivery_title', models.CharField(default='Доставка', max_length=200, verbose_name="Заголовок блока 'Доставка'")),
                ('delivery_text', models.TextField(default='Мы предлагаем удобную доставку готовых блюд...', verbose_name="Текст блока 'Доставка'")),
                ('delivery_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name="Изображение блока 'Доставка'")),
            ],
            options={
                'verbose_name': 'Контент главной страницы',
                'verbose_name_plural': 'Контент главной страницы',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Pro🥑ПИТАНИЕ', max_length=200, verbose_name='Название сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Логотип')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Фавикон')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Ссылка на Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Ссылка на Telegram')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='Ссылка на WhatsApp')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
